baseURL = "https://arthurbryan.com/"
languageCode = "en-us"
title = "Arthur Bryan"

[params]
  author = "Arthur Bryan"
  description = "Cloud Infrastructure Engineer | AWS | Python | Linux | Automation"
  tagline = "Building and automating cloud infrastructure"
  motto = "Automate everything, document the rest"
  github = "https://github.com/arthur-bryan"
  linkedin = "https://www.linkedin.com/in/arthur-bryan/"
  youtube = "https://www.youtube.com/@arthurbryan5208"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
